#config_version=5
show_player:
  mode_attract_started:
    attract_dmd_loop:
      loops: -1
      speed: 1
  mode_attract_started.1: 
    attract_light_show:
      loops: -1
      speed: 6 


  mode_attract_stopped:
    attract_dmd_loop:
      action: stop
  mode_attract_stopped.1: 
    attract_light_show:
      action: stop

