#config_version=5
mode_settings:
  keep_multiplier: True
  display_delay_ms: 1s
  bonus_entries:
      - event: bonus_ramps
        score: 1000 * current_player.multiplier
        player_score_entry: bonus
        reset_player_score_entry: True


slide_player:
  bonus_start: slide_6
  bonus_ramps: slide_7
  bonus_subtotal: slide_9
  bonus_multiplier: slide_10
  bonus_total: slide_11
slides:
  slide_6:
  - type: text
    text: END OF BALL BONUS
  slide_7:
  - type: text
    text: 'BONUS:(bonus) MULTIPLIER:(multiplier)'
  slide_9:
  - type: text
    text: 'BONUS SCORE: (score)'
    number_grouping: true
  slide_10:
  - type: text
    text: (multiplier)X
  slide_11:
  - type: text
    text: 'TOTAL BONUS: (score)'
    number_grouping: true
