#config_version=5
# July 31, 2021 set default_pulse_ms: (5-7 = Weak pulse, 10 = Medium, 15 = strong)
# Aug 31, Can't enable autofire flippers with EOS config
# Sept 28, 2021 Increase pulse on drop target bank coils from 15 to 25 ms
# Bank C (1-0-n)
autofire_coils:
  center_jet:
    coil: c_cjet
    switch: s_cjet
  left_jet:
    coil: c_ljet
    switch: s_ljet
  right_jet:
    coil: c_rjet
    switch: s_rjet
  left_slingshot:
    coil: c_lslingshot
    switch: s_lslingshot
  right_slingshot:
    coil: c_rslingshot
    switch: s_rslingshot

coils:
# Non autofired coil 0-0-n
# ---------------------------------------
# Solenoid Bank A (Non Autofired Coils)
# ---------------------------------------
# Outhole 
  c_outhole:
    number: 0-0-8
    label:
    tags:
    default_pulse_ms: 12
# Reset Left center drop when left inlane or lane 2 hit
  c_lcdropreset:
    number: 0-0-9
    label:
    tags:
    pulse_events: 
      - s_left_inlane_active
      - s_lane2_active
      - ball_started
    default_pulse_ms: 10
  c_lbdropreset1:
    number: 0-0-10
    label:
    tags:
    default_pulse_ms: 25
  c_lbdropreset2:
    number: 0-0-11
    label:
    tags:
    default_pulse_ms: 25
  c_rbdropreset1:
    number: 0-0-0
    label:
    tags:
    default_pulse_ms: 25
  c_rbdropreset2:
    number: 0-0-12
    label:
    tags:
    default_pulse_ms: 25
# Reset right center drop when left inlane or lane 2 hit or begin of game
  c_rcdropreset:
    number: 0-0-13
    label:
    tags:
    pulse_events: 
      - s_right_inlane_active
      - s_lane4_active
      - ball_started
    default_pulse_ms: 10
# See settings.replay_score in config.yaml, fire knocker if replay or extraball awarded or match awarded (Display credit_added slide)

# Knocker
  c_knocker:
    pulse_events: 
      - replay
      - extra_ball_score_one_awarded
      - match_has_match
    number: 0-0-14
    label:
    tags:
    default_pulse_ms: 9

# ---------------------------------------    
# Solenoid Bank B (Non Autofired Coils)
# ---------------------------------------
  c_relay1:
    number: 0-0-15
    label:
    tags:
    default_hold_power: 1.0
  c_relay2:
    number: 0-0-7
    label:
    tags:
    default_hold_power: 1.0   


# ---------------------------------------    
# Solenoid Bank C Auto fired coils 1-0-n
# ---------------------------------------
  c_flipper_left_main:
    number: 1-0-0
    default_pulse_ms: 5
    allow_enable: true
    default_hold_power: 1.0
  c_flipper_right_main:
    number: 1-0-7
    default_pulse_ms: 5
    allow_enable: true
    default_hold_power: 1.0

# Bumpers
  c_ljet:
    number: 1-0-6
    label:
    tags:
    default_pulse_ms: 10
  c_cjet:
    number: 1-0-5
    label:
    tags:
    default_pulse_ms: 10
  c_rjet:
    number: 1-0-4
    label:
    tags:
    default_pulse_ms: 10

# Left slingshot 
  c_lslingshot:
    number: 1-0-3
    default_pulse_ms: 7

# Right slingshot (Working)
  c_rslingshot:
    number: 1-0-2
    default_pulse_ms: 7

    


