#config_version=5
#
# 1978 Williams Phoenix Pinball 
# Mission Pinball Framework Version .54 April 2021
# Author: Todd Legere
# Instructions:
# 1) Spell PHOENIX by completing Top LANES 1 thru 5
# 2) When E of PHONEIX is lit hit Bulls Eye for Extra ball
# 3) When I is lit outlanes alternate for SPECIAL (50,000 pts)
# 4) When X is lit hit Bulls eye for SPECIAL (50,000 pts)
# 5) Make either 4 left or 4 right drop targets advance Multiplier 2x,3x,4x,5x
# 6) Spinner 100pts, Increases to 1000pts when 10 or greater bonus pts (stops after 20)
#
# To test virtual machine version start two terminal sesssions 
# 1) mpf both -X 
# 2) mpf monitor
# On the virtual monitor you will find virtual buttons for 
# Start, Coins, ShutdownPC, Service Coin door open, Service_enter, Service_esc, Service_down, Service_up
# See Operators manual in this folder for details
# An extra credit is awarded at end of game if score greater than replay score (See setting replay score) and credits
# 
# To execute component test (make sure you are in phoenix folder)
# python3 -m unittest discover
#

dmds:
  dmd:
    shades: 16
    fps: 24

config:
- hardware.yaml
- keyboard.yaml

smart_virtual:
  file_log: full

mpf:
  default_pulse_ms: 20


modes:
- base
- attract
- bonus
- high_score
- tilt
- droptargets
- spell_phoenix
- service
- credits
- match
- shoot_again
- shutdown_computer

player_vars:
# No replay at settings.replay_score_level1 awarded yet
  replay_level_1:
    initial_value: 0
# Used in shoot_again.yaml & set in spell_phoenix.yaml and reset in base.yaml
  my_extraball_awarded:
    initial_value: 0
# Spinner value Initial value 100 increases to 1,000 when 10,000 playfield bomus lamp lit
  spinner_value:
    initial_value: 100
# See base.yaml & spell_phoenix.yaml for bullseye_bonus start val 5,000 to max 40,000
  bullseye_bonus:
    initial_value: 5000
# See mode/droptarget.yaml, Drop all 4 drop targets & increase multiplier. start value 1 to max 5
  my_multiplier:
    value_type: int
    initial_value: 1
  multiplier:
    value_type: int
    initial_value: 1
  bonus:
    value_type: int
    initial_value: 0
# Turn on extra ball lamp when letter E lite give extra if Bullseye hit
  extraball_lamp_on:
    value_type: int
    initial_value: 0
# Turn on spinner lamp when bonus >=10 and bonus <=20
  spinner_lamp_on:
    value_type: int
    initial_value: 0

# Used by service mode (Adjustments) replay score, # of balls, max_credits (settings)
settings:
  replay_score:
    label: Replay Score
    values:
      230000: "230000 (default)"
      330000: "330000"
      500000: "500000"
    default: 230000
    key_type: int
    sort: 100
  balls_per_game:
    label: Balls per game
    values:
      3: "3 (default)"
      5: "5"
    default: 3
    key_type: int
    sort: 100

# Used by credits.yaml
  max_credits:
    label: Max Credits
    values:
      10: "10"
      20: "20 (Default)"
    default: 20
    key_type: int
    sort: 100

# Service Menu (Adjustments) allows changing # balls per game 
game:
  balls_per_game: 3 if settings.balls_per_game==0 else settings.balls_per_game
  max_players: 4

# Service Menu (Adjustments) allows changing credits 
credits:
  max_credits: 20 if settings.max_credits==0 else settings.max_credits
# Set To coins required. Change free_play: true for Free play (I prefer adding coins)
  free_play: false
  price_tier_template: "{{credits}} CREDITS ${{price}}"
# Give free credit by pressing s_service_esc switch
  service_credits_switch: s_service_esc
  switches:
    - switch: s_left_coin
      type: dollars
      value: .25
    - switch: s_right_coin
      type: dollars
      value: 1
  pricing_tiers:
    - price: .50
      credits: 1
    - price: 2
      credits: 5
  events:
    - event: add_credit
      type: award
      credits: 1
    - event: match_has_match
      type: award
      credits: winners
    - event: special
      type: special
      credits: 1
    - event: game_ending{current_player.score > settings.replay_score}
      type: award
      credits: 1
    - event: high_score_credit
      type: high_score
      credits: 1
    - event: match
      type: match
      credits: 1
  fractional_credit_expiration_time: 15m
  credit_expiration_time: 2h
  persist_credits_while_off_time: 1h
  free_play_string: FREE PLAY
  credits_string: CREDITS

widget_styles:
  text_default:
    font_name: Quadrit
    font_size: 10
    adjust_top: 2
    adjust_bottom: 3
  space_title_huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    adjust_top: 3
    adjust_bottom: 3
  space_title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    adjust_top: 2
    adjust_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    adjust_top: 1
    adjust_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    adjust_top: 2
    adjust_bottom: 3
  tall_title:
    font_name: big_noodle_titling
    font_size: 20

#
# Sound settings
#
sound_system:
  tracks:
    voice:
      volume: 1
      priorsounity: 2
      simultaneous_sounds: 1
      preload: true
    sfx:
      volume: 1
      priority: 1
      preload: true
      simultaneous_sounds: 7
    music:
      volume: 1
      simultaneous_sounds: 1
  buffer: 2048  # previous value was 512
  frequency: 44100
  channels: 1
  master_volume: 1
  enabled: true

assets:
  sounds:
    default:
      track: sfx
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice
