#config_version=5
# Added knocker pulse if score > settings.replay_score
# Added raise lcdrop & rcdrop
# Last updated Apr 3, 2021

machine:
  balls_installed: 5
  min_balls: 1

virtual_platform_start_active_switches: s_outhole

mpf-mc:
  fps: 60

window:
  width: 800 
#  width: 600
  height: 600
#  height: 200
  title: Mission Pinball Framework - PHOENIX
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: window

displays:
  window:
    width: 800
    height: 600
  dmd:
    width: 128
    height: 32
    default: true


light_player:
  s_lane1_active:
    l_lane1: ff
  s_lane2_active:
    l_lane2: ff
  s_lane3_active:
    l_lane3: ff
  s_lane4_active:
    l_lane4: ff
  s_lane5_active:
    l_lane5: ff

drop_targets:
  left_drop1:
    switch: s_lbdrop1
    debug: True
  left_drop2:
    switch: s_lbdrop2
    debug: True
  left_drop3:
    switch: s_lbdrop3
    debug: True
  left_drop4:
    switch: s_lbdrop4
    debug: True
  right_drop1:
    switch: s_rbdrop1
    debug: True
  right_drop2:
    switch: s_rbdrop2
    debug: True
  right_drop3:
    switch: s_rbdrop3
    debug: True
  right_drop4:
    switch: s_rbdrop4
    debug: True
  left_center_drop:
    switch: s_lcdrop
    reset_coil: c_lcdropreset
    reset_events: drop_target_left_center_drop_down
  right_center_drop:
    switch: s_rcdrop
    reset_coil: c_rcdropreset
    reset_events: drop_target_right_center_drop_down

drop_target_banks:
  left_bank:
    drop_targets: left_drop1, left_drop2, left_drop3, left_drop4
# Reminder there are 2 banks of coils , c_lbdropreset2
    reset_coils: c_lbdropreset1
    reset_on_complete: 1s
  right_bank:
    drop_targets: right_drop1, right_drop2, right_drop3, right_drop4
# Reminder there are 2 banks of coils , c_rbdropreset2
    reset_coils: c_rbdropreset1
    reset_on_complete: 1s

switches:
# Fliptronics
  s_flipper_right_eos:
    number: sf1
    tags:
    label:
  s_flipper_right:
    number: sf2
    tags: player, high_score_right, right_flipper
    label:
  s_flipper_left_eos:
    number: sf3
    tags:
    label:
  s_flipper_left:
    number: sf4
    tags: player, high_score_left, left_flipper
    label:

# Service Sqwitches
  s_door_open:
    number: 
    tags: service_door_open, power_off
  s_service_enter:
    number: 
    tags: service_enter
  s_service_esc:
    number: 
    tags: service_esc
  s_service_up:
    number: 
    tags: service_up
  s_service_down:
    number: 
    tags: service_down
  s_shutdown:
    number:
# Matrix
  s_plumb_bob:
    number: s1
    label:
    tags: tilt_warning
  s_ball_tilt:
    number: s2
    label:
    tags: tilt_warning
  s_start:
    number: s3
    label:
    tags: start, player, high_score_select
  s_right_coin:
    number: s4
    tags:
    label:
  s_center_coin:
    number: s5
    tags:
    label:
  s_left_coin:
    number: s6
    tags:
    label:
  s_slam_tilt:
    number: s7
    tags: 
  s_highscore_reset:
    number: s8
    tags:
    label:
  s_lane1:
    number: s9
    label:
  s_lane2:
    number: s10
    label:
  s_lane3:
    number: s11
    label:
  s_lane4:
    number: s12
    label:
  s_lane5:
    number: s13
    label:
# Right and left top targets auto enables top middle lane3 (Sw14 and Sw19)
  s_rtarget:
    number: s14
    tags:
    label:
  s_spinner:
    number: s15
    label:
# bumpers
  s_rjet:
    number: s16
    label:
    tags: jet
  s_cjet:
    number: s17
    label:
    tags: jet
  s_ljet:
    number: s18
    label:
    tags: jet
# Right and left top targets auto enables top lane3
  s_ltarget:
    number: s19
    tags:
    label:
  s_lstandup:
    number: s20
    tags:
    label:
  s_bullseye:
    number: s21
    tags:
    label:
  s_lbstandup:
    number: s22
    tags:
    label:
  s_playfieldtilt:
    number: s23
    tags:
    label:
  s_rbstandup:
    number: s24
    tags:
    label:
# Leftbank drop targets (1-4)
  s_lbdrop1:
    number: s25
    tags:
    label:
  s_lbdrop2:
    number: s26
    tags:
    label:
  s_lbdrop3:
    number: s27
    tags:
    label:
  s_lbdrop4:
    number: s28
    tags:
    label:
  s_lbdropall:
    number: s29
    tags:
    label:
  s_lslingshot:
    number: s30
    label:
    tags: slingshot
  s_left_inlane:
    number: s31
    label:
  s_left_outlane:
    number: s32
    label:
    tags: playfield_active, outlane
# Left and Right Center drop targets
  s_lcdrop:
    number: s33
    label:
    tags: 
  s_rcdrop:
    number: s35
    label:
    tags: 
  s_outhole:
    number: s37
    label:
    tags: 
# Lane 4 Conditional standup Right center drop target
  s_trstandup:
    number: s38
    label:
    tags: 
  s_bottom_left_standup:
    number: s39
    label:
    tags: 
  s_bottom_right_standup:
    number: s40
    label:
    tags: 
# Rightbank drop targets (1-4)
  s_rbdrop1:
    number: s41
    tags:
    label:
  s_rbdrop2:
    number: s42
    tags:
    label:
  s_rbdrop3:
    number: s43
    tags:
    label:
  s_rbdrop4:
    number: s44
    tags:
    label:
  s_rbdropall:
    number: s45
    tags:
    label:
  s_rslingshot:
    number: s46
    label:
    tags: slingshot
  s_right_inlane:
    number: s47
    label:
  s_right_outlane:
    number: s48
    label:
    tags: playfield_active, outlane

lights:
  l_lane1:
    number: l1
    label:
    tags: red
  l_lane2:
    number: l2
    label:
    tags: red
  l_lane3:
    number: l3
    label:
    tags: red
  l_lane4:
    number: l4
    label:
    tags: red
  l_lane5:
    number: l5
    label:
    tags: red
  l_P:
    number: l6
    label:
    tags: red
  l_H:
    number: l7
    label:
    tags: red
  l_O:
    number: l8
    label:
    tags: red
  l_E:
    number: l9
    label:
    tags: red
  l_N:
    number: l10
    label:
    tags: red
  l_I:
    number: l11
    label:
    tags: red
  l_X:
    number: l12
    label:
    tags: red
  l_bonus1:
    number: l13
    label:
    tags: red
  l_bonus2:
    number: l14
    label:
    tags: red
  l_bonus3:
    number: l15
    label:
    tags: red
  l_bonus4:
    number: l16
    label:
    tags: red
  l_bonus5:
    number: l17
    label:
    tags: red
  l_bonus6:
    number: l18
    label:
    tags: red
  l_bonus7:
    number: l20
    label:
    tags: red
  l_bonus8:
    number: l21
    label:
    tags: red
  l_bonus9:
    number: l22
    label:
    tags: red
  l_bonus10:
    number: l23
    label:
    tags: red
  l_bonus20:
    number: l24
    label:
    tags: red
  l_spinner:
    number: l25
    label:
    tags: red
  l_extraball:
    number: l26
    label:
    tags: red
  l_shotagain:
    number: l27
    label:
    tags: red
  l_lspecial:
    number: l28
    label:
    tags: red
  l_rspecial:
    number: l29
    label:
    tags: red
  l_multiplier2x:
    number: l30
    label:
    tags: red
  l_multiplier3x:
    number: l31
    label:
    tags: red
  l_multiplier4x:
    number: l32
    label:
    tags: red
  l_multiplier5x:
    number: l33
    label:
    tags: red

coils:
  c_outhole:
    number: c01
    label:
    tags:
    default_pulse_ms: 25
# Reset Left center drop when left inlane or lane 2 hit
  c_lcdropreset:
    number: c02
    label:
    tags:
    pulse_events: 
      - s_left_inlane_active
      - s_lane2_active
    default_pulse_ms: 25
  c_lbdropreset1:
    number: c03
    label:
    tags:
    default_pulse_ms: 25
  c_lbdropreset2:
    number: c04
    label:
    tags:
    default_pulse_ms: 25
  c_rbdropreset1:
    number: c05
    label:
    tags:
    default_pulse_ms: 25
  c_rbdropreset2:
    number: c06
    label:
    tags:
    default_pulse_ms: 25
# Reset right center drop when left inlane or lane 2 hit
  c_rcdropreset:
    number: c07
    label:
    tags:
    pulse_events: 
      - s_right_inlane_active
      - s_lane4_active
    default_pulse_ms: 25
# Sounds triggers by solenoid
  c_10pt:
    number: c09
    label:
    tags:
    default_pulse_ms: 25
  c_100pt:
    number: c10
    label:
    tags:
    default_pulse_ms: 25
  c_1kpt:
    number: c11
    label:
    tags:
    default_pulse_ms: 25
  c_10kpt:
    number: c12
    label:
    tags:
    default_pulse_ms: 25
  c_altsound:
    number: c13
    label:
    tags:
    default_pulse_ms: 25
# See settings.replay_score in config.yaml, fire knocker if replay or extraball awarded or match awarded (Display credit_added slide)
  c_knocker:
    pulse_events: 
      - replay
      - extra_ball_score_one_awarded
      - match_has_match
    number: c14
    label:
    tags:
# Bumpers
  c_ljet:
    number: c17
    label:
    tags:
  c_cjet:
    number: c18
    label:
    tags:
  c_rjet:
    number: c19
    label:
    tags:
# Left and right slingshoot
  c_lslingshot:
    number: c20
    label:
    tags:
  c_rslingshot:
    number: c21
    label:
    tags:

# Fliptronics coils
  c_flipper_left_main:
    number: fllm
    label:
    tags:
    default_pulse_ms: 30
  c_flipper_left_hold:
    number: fllh
    label:
    tags:
    max_hold_power: 1.0
  c_flipper_right_main:
    number: flrm
    label:
    tags:
    default_pulse_ms: 30
  c_flipper_right_hold:
    number: flrh
    label:
    tags:
    max_hold_power: 1.0

playfields:
  playfield:
    default_source_device: trough
    tags: default

ball_devices:
  trough:
    eject_coil: c_outhole
    ball_switches: s_outhole
    debug: true
    tags: trough, home, drain

autofire_coils:
  left_slingshot:
    coil: c_lslingshot
    switch: s_lslingshot
  right_slingshot:
    coil: c_rslingshot
    switch: s_rslingshot
  center_jet:
    coil: c_cjet
    switch: s_cjet
  left_jet:
    coil: c_ljet
    switch: s_ljet
  right_jet:
    coil: c_rjet
    switch: s_rjet

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_flipper_right

slides:
  window_slide_1:
  - type: display
    width: 512
    height: 128
    effects:
      - type: dmd
        dot_color: ff5500
        background_color: 220000
  - type: text
    style: tall_title
    text: MISSION PINBALL FRAMEWORK
    anchor_y: top
    y: top-3
    font_size: 30
    color: white
  - type: rectangle
    width: 514
    height: 130
    color: 444444
  - type: text
    style: tall_title
    text: PHOENIX
    anchor_x: right
    anchor_y: bottom
    y: bottom+3
    x: right-42
    font_size: 30
    color: red

  waiting_for_connection:
  - type: text
    text: WAITING FOR MPF CONNECTION

  asset_status:
  - type: text
    text: "LOADING ASSETS: (percent)%"

slide_player:
  mc_ready:
    window_slide_1:
      target: window
  loading_assets: asset_status


